/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  userManualSidebar: [
    {
      type: 'doc',
      label: '开始',
      id: 'user-manual/getting-started',
    },
    {
      type: 'doc',
      label: '安装',
      id: 'user-manual/installation',
    },
    {
      type: 'doc',
      label: '模拟器支持',
      id: 'user-manual/emulator-support',
    },
    {
      type: 'doc',
      label: '常见问题',
      id: 'user-manual/frequently-asked-questions',
    },
    {
      type: 'doc',
      label: '任务列表',
      id: 'user-manual/task-list',
    },
    {
      type: 'doc',
      label: '问题反馈',
      id: 'user-manual/issue-reporting',
    },
  ],

  developmentSidebar: [
    {
      type: 'doc',
      label: '导言',
      id: 'development/preamble',
    },
    {
      type: 'doc',
      label: 'Pull Request',
      id: 'development/pull-request',
    },
    {
      type: 'doc',
      label: '用户选项',
      id: 'development/user-option',
    },
    {
      type: 'doc',
      label: '操控设备',
      id: 'development/manipulation-device',
    },
    {
      type: 'doc',
      label: '过程元素',
      id: 'development/process-element',
    },
    {
      type: 'doc',
      label: '调试',
      id: 'development/debugging',
    },
    {
      type: 'doc',
      label: '日志系统',
      id: 'development/log',
    },
    {
      type: 'doc',
      label: '异常',
      id: 'development/exception',
    },
    {
      type: 'doc',
      label: '装饰器',
      id: 'development/decorators',
    },
    {
      type: 'doc',
      label: '开发工具',
      id: 'development/dev-tools',
    },
    {
      type: 'doc',
      label: '游戏逻辑复用',
      id: 'development/game-logic-reuse',
    },
    {
      type: 'doc',
      label: '编写任务示例',
      id: 'development/task-example',
    },
  ]
};

module.exports = sidebars;
